/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./js/**/*.js"],
  theme: {
    extend: {
      colors: {
        bg:      'var(--bg)',
        surface: 'var(--surface)',
        surface2:'var(--surface2)',
        border:  'var(--border)',
        text:    'var(--text)',
        muted:   'var(--muted)',
        blue:    'var(--blue)',
        green:   'var(--green)',
        amber:   'var(--amber)',
        red:     'var(--red)',
        purple:  'var(--purple)',
      },
      fontFamily: {
        sans: ['Space Grotesk', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      fontSize: {
        'clamp-h1': 'clamp(3rem, 8vh, 7rem)',
        'clamp-badge': 'clamp(0.8rem, 1.6vh, 1.1rem)',
        'clamp-clock': 'clamp(1.1rem, 2.8vh, 2rem)',
        'clamp-sync': 'clamp(0.85rem, 1.7vh, 1.15rem)',
        'clamp-status': 'clamp(0.75rem, 1.5vh, 1rem)',
        'clamp-kpi-label': 'clamp(0.8rem, 1.6vh, 1.1rem)',
        'clamp-kpi-value': ['clamp(2.5rem, 10vh, 8rem)', { lineHeight: '0.85' }],
        'clamp-kpi-sub': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-legend': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-hero-label': 'clamp(0.9rem, 1.9vh, 1.3rem)',
        'clamp-hero-value': ['clamp(4.5rem, 17vh, 13rem)', { lineHeight: '0.85' }],
        'clamp-hero-sub': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-hero-list': 'clamp(0.9rem, 1.8vh, 1.25rem)',
        'clamp-th': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-order-id': 'clamp(0.9rem, 1.9vh, 1.3rem)',
        'clamp-order-client': 'clamp(0.95rem, 2vh, 1.4rem)',
        'clamp-order-date': 'clamp(0.85rem, 1.7vh, 1.15rem)',
        'clamp-order-imp': 'clamp(0.85rem, 1.6vh, 1.1rem)',
        'clamp-chip': 'clamp(0.7rem, 1.4vh, 0.9rem)',
        'clamp-emp-name': 'clamp(0.95rem, 2vh, 1.4rem)',
        'clamp-emp-count': 'clamp(0.85rem, 1.6vh, 1.1rem)',
        'clamp-task-text': 'clamp(1.25rem, 2.6vh, 1.9rem)',
        'clamp-task-status': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-task-deadline': 'clamp(0.75rem, 1.6vh, 1.1rem)',
        'clamp-prio': 'clamp(0.8rem, 1.6vh, 1.1rem)',
        'clamp-col-title': 'clamp(0.9rem, 1.8vh, 1.3rem)',
        'clamp-col-count': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-ev-time': 'clamp(0.85rem, 1.7vh, 1.15rem)',
        'clamp-ev-title': 'clamp(0.95rem, 2vh, 1.4rem)',
        'clamp-ev-meta': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-dep-date': 'clamp(0.85rem, 1.7vh, 1.15rem)',
        'clamp-dep-day': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-dep-title': 'clamp(0.95rem, 2vh, 1.4rem)',
        'clamp-dep-meta': 'clamp(0.8rem, 1.5vh, 1rem)',
        'clamp-dep-badge': 'clamp(0.75rem, 1.5vh, 1rem)',
        'clamp-toast-title': 'clamp(0.9rem, 1.8vh, 1.2rem)',
        'clamp-toast-msg': 'clamp(0.75rem, 1.4vh, 0.95rem)',
        'clamp-rotate': 'clamp(0.75rem, 1.5vh, 1rem)',
        'clamp-empty': '1rem',
      },
      spacing: {
        'vh-1': '1vh',
        'vh-1-2': '1.2vh',
        'vh-1-5': '1.5vh',
        'vh-2': '2vh',
        'vh-2-5': '2.5vh',
        'vh-3': '3vh',
        'vh-4': '4vh',
        'vh-5': '5vh',
        'vw-2-5': '2.5vw',
        'vw-3-5': '3.5vw',
        'vw-1-2': '1.2vw',
        'vw-1-8': '1.8vw',
        'vw-2': '2vw',
      },
      borderWidth: {
        '3': '3px',
      },
      borderRadius: {
        '100': '100px',
        '12': '12px',
        '8': '8px',
        '4': '4px',
        '2': '2px',
      },
      boxShadow: {
        'card': '0 2px 8px rgba(0, 0, 0, 0.04)',
        'toast': '0 4px 12px rgba(0, 0, 0, 0.08)',
        'btn': '0 2px 10px rgba(0, 0, 0, 0.05)',
        'urgent': '0 4px 12px rgba(220, 38, 38, 0.08)',
        'sync': '0 0 6px currentColor',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        flashFill: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.1' },
        },
        colIn: {
          from: { opacity: '0', transform: 'translateY(14px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        cardIn: {
          from: { opacity: '0', transform: 'translateX(-6px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        rowIn: {
          from: { opacity: '0', transform: 'translateX(-8px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        colInOrders: {
          from: { opacity: '0', transform: 'translateY(14px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        cardInOrders: {
          from: { opacity: '0', transform: 'translateX(-6px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        blink: 'blink 2s infinite',
        spin: 'spin 0.8s linear infinite',
        flashFill: 'flashFill 0.7s ease',
        colIn: 'colIn 0.45s ease both',
        cardIn: 'cardIn 0.4s ease both',
        rowIn: 'rowIn 0.35s ease both',
        colInOrders: 'colInOrders 0.45s ease both',
        cardInOrders: 'cardInOrders 0.5s ease both',
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(rgba(37, 99, 235, 0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(37, 99, 235, 0.04) 1px, transparent 1px)',
      },
      backgroundSize: {
        '50': '50px',
      },
      zIndex: {
        '1': '1',
      },
      transitionTimingFunction: {
        'cubic': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      scale: {
        '98': '0.98',
        '102': '1.02',
      },
    },
  },
  plugins: [],
  // Disable Preflight to keep default browser styles
  corePlugins: {
    preflight: false,
  },
}
